repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff-format
      - id: ruff
        args:
          - --fix
          - --unsafe-fixes

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args:
          - --in-place
          - --expand-star-imports  # ruff can't do this yet
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: local
    hooks:
      # run mypy locally so it uses the local venv
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or: [python, pyi]
      # run pylint locally so it uses local venv
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types_or: [python, pyi]
