# Guide: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "jamjam"
version = "0.0.1"
readme = 'README.md'
license = { file = 'LICENSE' } # from https://choosealicense.com/licenses/gpl-3.0/

requires-python = ">=3.11"
dependencies = []


[project.optional-dependencies]
dev = ["mypy", "pre-commit", "pylint", "pytest"]


[project.scripts]
"jj.info" = "jamjam._scripts.info:main"


[tool.mypy]
# see: https://mypy.readthedocs.io/en/stable/config_file.html
allow_redefinition = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
implicit_reexport = true
pretty = true
show_column_numbers = true
show_error_code_links = true
show_error_codes = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true


[tool.ruff]
# see: https://docs.astral.sh/ruff/rules/
target-version = "py311"
output-format = "concise"
format.preview = true

lint.select = ["ALL"]
lint.ignore = [
    "ANN401",  # any-type; genuine usecases for `Any` when the type-system fails
    "COM812",  # missing-trailing-comma; inccompatable with auto-formatters
    "D203",    # one-blank-line-before-class; incompatable with chosen docs style
    "D213",    # multi-line-summary-second-line; incompatable with chosen docs style
    "PLR2004", # magic-value-comparison; fine for tests
    "S101",    # assert; fine for tests
    "T201",    # print; fine for scripts
    "TCH003",  # typing-only-standard-library-import; I use `TYPE_CHECKING` as necessary not as default
]


[tool.pylint.main]
# see: https://pylint.pycqa.org/en/latest/user_guide/messages/messages_overview.html
enable = ["all"]
disable = [
    "missing-class-docstring",    # TODO: may enable docstring checks later
    "missing-function-docstring", # TODO: may enable docstring checks later
    "missing-kwoa",               # conflicts with type-checkers
    "missing-module-docstring",   # TODO: may enable docstring checks later
    "too-few-public-methods",     # small classes are fine
    "too-many-function-args",     # conflicts with type-checkers
]
